name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.4
    - name: Build with Gradle
      run: ./gradlew sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Post Slack messages
      uses: pullreminders/slack-action@v1.0.7
      if: github.ref == 'refs/heads/main' && failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        args: '{"channel":"C1JUCTD5E","text":"*Build Failed!*\nA recent push to <https://github.com/momentumfrc/2022RapidReact/tree/main|momentumfrc/2022RapidReact/tree/main> failed to compile"}'